export default function TermsPage() {
  return (
    <div style={{ background: '#F8FAFC', minHeight: '100vh' }}>
      <div style={{ maxWidth: 700, margin: '0 auto', padding: '48px 24px' }}>
        <h1 style={{ fontSize: 32, fontWeight: 800, color: '#1E293B', margin: '0 0 24px', fontFamily: 'Georgia, serif' }}>Terms of Service</h1>
        <div style={{ background: '#fff', borderRadius: 16, padding: 32, border: '1px solid #E2E8F0', lineHeight: 1.8, color: '#374151', fontSize: 15 }}>
          <p><strong>Last updated:</strong> March 2026</p>

          <h2 style={{ fontSize: 20, fontWeight: 700, color: '#1E293B', marginTop: 24 }}>Use of Service</h2>
          <p>SAT ACT MathAI provides free AI-powered math preparation for the SAT and ACT exams. By using this service, you agree to these terms.</p>

          <h2 style={{ fontSize: 20, fontWeight: 700, color: '#1E293B', marginTop: 24 }}>AI-Generated Content</h2>
          <p>Questions and feedback are generated by AI. While we strive for accuracy, AI-generated content may occasionally contain errors. SAT ACT MathAI is a supplementary study tool and should be used alongside official preparation materials.</p>

          <h2 style={{ fontSize: 20, fontWeight: 700, color: '#1E293B', marginTop: 24 }}>Disclaimer</h2>
          <p>SAT ACT MathAI is not affiliated with, endorsed by, or associated with the College Board (SAT) or ACT, Inc. SAT is a registered trademark of the College Board. ACT is a registered trademark of ACT, Inc.</p>

          <h2 style={{ fontSize: 20, fontWeight: 700, color: '#1E293B', marginTop: 24 }}>Limitation of Liability</h2>
          <p>SAT ACT MathAI is provided &quot;as is&quot; without warranties. We are not responsible for any test outcomes. Use this tool as part of a comprehensive study plan.</p>

          <h2 style={{ fontSize: 20, fontWeight: 700, color: '#1E293B', marginTop: 24 }}>Contact</h2>
          <p>Questions about these terms? Email <a href="mailto:support@satactmathai.com" style={{ color: '#2563EB' }}>support@satactmathai.com</a>.</p>
        </div>
      </div>
    </div>
  )
}
