import Container from '@/components/ui/Container'
import Eyebrow from '@/components/ui/Eyebrow'

export const metadata = {
  title: 'Terms of Service — SATACTMathAI',
  description: 'The terms that govern your use of SATACTMathAI.',
}

export default function TermsPage() {
  return (
    <Container className="py-20 max-w-[760px]">
      <Eyebrow className="mb-5">Last updated · March 2026</Eyebrow>
      <h1 className="headline text-[42px] mb-10">Terms of <em>service</em>.</h1>

      <article className="prose-legal">
        <h2>Use of service</h2>
        <p>SATACTMathAI provides AI-powered math preparation for the SAT and ACT. By using this service you agree to these terms.</p>

        <h2>AI-generated content</h2>
        <p>Questions and feedback are generated by AI. We aim for accuracy, but content may occasionally contain errors. Treat SATACTMathAI as a supplementary tool alongside official preparation materials.</p>

        <h2>Disclaimer</h2>
        <p>SATACTMathAI is not affiliated with, endorsed by, or associated with the College Board (SAT) or ACT, Inc. SAT is a registered trademark of the College Board. ACT is a registered trademark of ACT, Inc.</p>

        <h2>Limitation of liability</h2>
        <p>The service is provided &ldquo;as is&rdquo; without warranties. We are not responsible for test outcomes. Use the tool as part of a comprehensive study plan.</p>

        <h2>Contact</h2>
        <p>Questions about these terms? <a href="mailto:support@satactmathai.com">support@satactmathai.com</a>.</p>
      </article>

      <style>{`
        .prose-legal h2 { font-family: var(--font-serif); font-size: 22px; font-weight: 600; margin: 32px 0 10px; color: var(--color-ink); border-top: 1px solid var(--color-rule); padding-top: 24px; }
        .prose-legal h2:first-child { border-top: 0; padding-top: 0; margin-top: 0; }
        .prose-legal p { font-size: 15px; line-height: 1.75; color: var(--color-ink-2); margin: 8px 0; }
        .prose-legal a { color: var(--color-marker); border-bottom: 1px solid var(--color-marker); }
      `}</style>
    </Container>
  )
}
