export const satTopics = [
  // ALGEBRA
  { name: "Linear Equations in One Variable", domain: "Algebra", domainSlug: "algebra", slug: "linear-equations-one-variable" },
  { name: "Linear Equations in Two Variables", domain: "Algebra", domainSlug: "algebra", slug: "linear-equations-two-variables" },
  { name: "Linear Functions", domain: "Algebra", domainSlug: "algebra", slug: "linear-functions" },
  { name: "Systems of Two Linear Equations", domain: "Algebra", domainSlug: "algebra", slug: "systems-two-linear-equations" },
  { name: "Linear Inequalities in One Variable", domain: "Algebra", domainSlug: "algebra", slug: "linear-inequalities-one-variable" },
  { name: "Linear Inequalities in Two Variables", domain: "Algebra", domainSlug: "algebra", slug: "linear-inequalities-two-variables" },
  { name: "Interpreting Slope and Y-Intercept", domain: "Algebra", domainSlug: "algebra", slug: "interpreting-slope-y-intercept" },
  { name: "Writing Linear Equations from Context", domain: "Algebra", domainSlug: "algebra", slug: "writing-linear-equations-context" },

  // ADVANCED MATH
  { name: "Quadratic Equations Standard Form", domain: "Advanced Math", domainSlug: "advanced-math", slug: "quadratic-equations-standard-form" },
  { name: "Quadratic Equations Vertex Form", domain: "Advanced Math", domainSlug: "advanced-math", slug: "quadratic-equations-vertex-form" },
  { name: "Quadratic Formula and Discriminant", domain: "Advanced Math", domainSlug: "advanced-math", slug: "quadratic-formula-discriminant" },
  { name: "Factoring Quadratics", domain: "Advanced Math", domainSlug: "advanced-math", slug: "factoring-quadratics" },
  { name: "Exponential Functions", domain: "Advanced Math", domainSlug: "advanced-math", slug: "exponential-functions" },
  { name: "Exponential Equations", domain: "Advanced Math", domainSlug: "advanced-math", slug: "exponential-equations" },
  { name: "Polynomial Expressions", domain: "Advanced Math", domainSlug: "advanced-math", slug: "polynomial-expressions" },
  { name: "Polynomial Equations", domain: "Advanced Math", domainSlug: "advanced-math", slug: "polynomial-equations" },
  { name: "Rational Expressions", domain: "Advanced Math", domainSlug: "advanced-math", slug: "rational-expressions" },
  { name: "Rational Equations", domain: "Advanced Math", domainSlug: "advanced-math", slug: "rational-equations" },
  { name: "Radical Expressions", domain: "Advanced Math", domainSlug: "advanced-math", slug: "radical-expressions" },
  { name: "Radical Equations", domain: "Advanced Math", domainSlug: "advanced-math", slug: "radical-equations" },
  { name: "Absolute Value Equations", domain: "Advanced Math", domainSlug: "advanced-math", slug: "absolute-value-equations" },
  { name: "Absolute Value Functions", domain: "Advanced Math", domainSlug: "advanced-math", slug: "absolute-value-functions" },
  { name: "Function Notation and Evaluation", domain: "Advanced Math", domainSlug: "advanced-math", slug: "function-notation-evaluation" },
  { name: "Domain and Range of Functions", domain: "Advanced Math", domainSlug: "advanced-math", slug: "domain-range-functions" },
  { name: "Transformations of Functions", domain: "Advanced Math", domainSlug: "advanced-math", slug: "transformations-functions" },
  { name: "Systems of Nonlinear Equations", domain: "Advanced Math", domainSlug: "advanced-math", slug: "systems-nonlinear-equations" },
  { name: "Equivalent Algebraic Expressions", domain: "Advanced Math", domainSlug: "advanced-math", slug: "equivalent-algebraic-expressions" },

  // PROBLEM SOLVING & DATA ANALYSIS
  { name: "Ratios and Proportional Relationships", domain: "Problem Solving and Data Analysis", domainSlug: "problem-solving-data-analysis", slug: "ratios-proportional-relationships" },
  { name: "Rates and Unit Conversions", domain: "Problem Solving and Data Analysis", domainSlug: "problem-solving-data-analysis", slug: "rates-unit-conversions" },
  { name: "Percentages Increase and Decrease", domain: "Problem Solving and Data Analysis", domainSlug: "problem-solving-data-analysis", slug: "percentages-increase-decrease" },
  { name: "Fractions and Operations", domain: "Problem Solving and Data Analysis", domainSlug: "problem-solving-data-analysis", slug: "fractions-operations" },
  { name: "Interpreting Tables and Two-Way Tables", domain: "Problem Solving and Data Analysis", domainSlug: "problem-solving-data-analysis", slug: "interpreting-tables-two-way-tables" },
  { name: "Scatterplots and Line of Best Fit", domain: "Problem Solving and Data Analysis", domainSlug: "problem-solving-data-analysis", slug: "scatterplots-line-best-fit" },
  { name: "Mean Median Mode and Range", domain: "Problem Solving and Data Analysis", domainSlug: "problem-solving-data-analysis", slug: "mean-median-mode-range" },
  { name: "Basic Probability", domain: "Problem Solving and Data Analysis", domainSlug: "problem-solving-data-analysis", slug: "basic-probability" },
  { name: "Conditional Probability", domain: "Problem Solving and Data Analysis", domainSlug: "problem-solving-data-analysis", slug: "conditional-probability" },
  { name: "Margin of Error and Sample Inference", domain: "Problem Solving and Data Analysis", domainSlug: "problem-solving-data-analysis", slug: "margin-error-sample-inference" },
  { name: "Data Distributions and Spread", domain: "Problem Solving and Data Analysis", domainSlug: "problem-solving-data-analysis", slug: "data-distributions-spread" },

  // GEOMETRY & TRIGONOMETRY
  { name: "Area and Perimeter of 2D Shapes", domain: "Geometry and Trigonometry", domainSlug: "geometry-trigonometry", slug: "area-perimeter-2d-shapes" },
  { name: "Volume of 3D Shapes", domain: "Geometry and Trigonometry", domainSlug: "geometry-trigonometry", slug: "volume-3d-shapes" },
  { name: "Angles Parallel Lines and Transversals", domain: "Geometry and Trigonometry", domainSlug: "geometry-trigonometry", slug: "angles-parallel-lines-transversals" },
  { name: "Triangle Properties", domain: "Geometry and Trigonometry", domainSlug: "geometry-trigonometry", slug: "triangle-properties" },
  { name: "Pythagorean Theorem", domain: "Geometry and Trigonometry", domainSlug: "geometry-trigonometry", slug: "pythagorean-theorem" },
  { name: "Right Triangle Trigonometry", domain: "Geometry and Trigonometry", domainSlug: "geometry-trigonometry", slug: "right-triangle-trigonometry" },
  { name: "Sine and Cosine of Complementary Angles", domain: "Geometry and Trigonometry", domainSlug: "geometry-trigonometry", slug: "sine-cosine-complementary-angles" },
  { name: "Radians and Degrees", domain: "Geometry and Trigonometry", domainSlug: "geometry-trigonometry", slug: "radians-degrees" },
  { name: "Circles Area Circumference Arc Length", domain: "Geometry and Trigonometry", domainSlug: "geometry-trigonometry", slug: "circles-area-circumference-arc-length" },
  { name: "Coordinate Geometry Midpoint and Distance", domain: "Geometry and Trigonometry", domainSlug: "geometry-trigonometry", slug: "coordinate-geometry-midpoint-distance" },
  { name: "Equations of Circles", domain: "Geometry and Trigonometry", domainSlug: "geometry-trigonometry", slug: "equations-of-circles" },
];
